apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziplink-postgres
  namespace: ziplink
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"