apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ziplink-repo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/powerm1nt/ZipLink.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ziplink-development
  namespace: flux-system
spec:
  interval: 10m
  path: "./k8s/overlays/development"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ziplink-repo
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ziplink-server
      namespace: ziplink
    - apiVersion: apps/v1
      kind: Deployment
      name: ziplink-web
      namespace: ziplink
    - apiVersion: apps/v1
      kind: Deployment
      name: ziplink-postgres
      namespace: ziplink
  timeout: 5m