apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: ziplink-base

namespace: ziplink

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- postgres-pvc.yaml
- postgres.yaml
- server.yaml
- web.yaml
- ingress.yaml
- monitoring.yaml
- ../aws/ecr-service-account.yaml
- ../aws/ecr-registry-helper.yaml

commonLabels:
  app.kubernetes.io/name: ziplink
  app.kubernetes.io/instance: ziplink
  app.kubernetes.io/managed-by: kustomize

images:
- name: ziplink-server
  newTag: latest
- name: ziplink-web
  newTag: latest